[conference]
CONFERENCE_NAME = "PyData Berlin 2025"
CONFERENCE_WEBSITE = "https://pydata.org/berlin2025/"
CONFERENCE_YEAR = 2025
VOLUNTEER_SHIRT_COLOR = "green"

[server]
GUILD = 1340999177139650561
CONFERENCE_SETUP_DONE = true

[pytanis]
PRETALX_EVENT_NAME = "berlin2025"

[logging]
LOG_LEVEL = "INFO"

# =====
# used by discord_bot/conference_setup.py script. [role_colors] must match the values in [roles]
[role_colors]
Organiser = "#ff9b00"  # orange
Volunteer = "#fac800"  # yellow
Attendee = "#3778be"  # blue
Speaker = "#00c8e1"  # mid blue
Session-Chair = "#a2d9ef"  # light blue
Sponsor = "#e199c3"  # light pink
On-Site = "#00aa41"  # green
Remote = "#96dc00"  # light green

# =====
# fill by running discord_bot/conference_setup.py
[roles]
Organiser = 1386648341777092702
Volunteer = 1386648343567929426
Attendee = 1386648344721489970
Speaker = 1386648345547771905
Session-Chair = 1386648347414233198
Sponsor = 1386648348647227453
On-Site = 1386648350270685246
Remote = 1386648351813926912

[registration]
REG_CHANNEL_ID = 1394333955683123270
REG_HELP_CHANNEL_ID = 1394333957457317900
# =====
REG_LOG_CHANNEL_ID = 1394333364538052618


[job_board]
JOB_BOARD_CHANNEL_ID = 1410336053197279303
JOB_BOARD_TESTING = false

[tickets]
TICKETS_BASE_URL="https://val.pydata-berlin.org"
TICKETS_REFRESH_ROUTE="/tickets/refresh_all/"
TICKETS_VALIDATION_ROUTE="/tickets/validate_attendee/"

[programme_notifications]
timezone = "Europe/Berlin"
timewarp = false  # true for testing
conference_days_first = "2025-09-01"
conference_days_last = "2025-09-03"
conference_afternoon_session_start_time = 13
# pretalx_event_name = "berlin2025"
pretalx_schedule_url = "https://pretalx.com/api/events/berlin2025/schedules/latest/?expand=slots,slots.room,slots.submission,slots.submission.speakers,slots.submission.submission_type,slots.submission.track"
pretalx_talk_url = "https://cfp.pydata.org/berlin2025/talk/{code}"
# conference_website_session_base_url = "https://2025.pycon.de/program/{slug}"
# conference_website_api_session_url = "https://2025.pycon.de/program/{code}"
video_url = "https://videos.pydata-berlin.org"

[[programme_notifications.notification_channels]]
webhook_id = "PROGRAMME_NOTIFICATIONS"
include_channel_in_embeds = true

# Kuppelsaal channel: 4560
[programme_notifications.rooms.4560]
webhook_id = "ROOM_4560"
discord_channel_id = "1394335693916082409"

# B09 channel: 4561
[programme_notifications.rooms.4561]
webhook_id = "ROOM_4561"
discord_channel_id = "1394335699158827059"

# B07-B08 channel: 4562
[programme_notifications.rooms.4562]
webhook_id = "ROOM_4562"
discord_channel_id = "1394335703453667541"

# B05-B06 channel: 4563
[programme_notifications.rooms.4563]
webhook_id = "ROOM_4563"
discord_channel_id = "1394335707191050353"
