[conference]
CONFERENCE_NAME = "PyCon DE & PyData 2025"
CONFERENCE_WEBSITE = "https://2025.pycon.de"
CONFERENCE_YEAR = 2025
VOLUNTEER_SHIRT_COLOR = "cream"

[server]
GUILD = 955933777706762280
CONFERENCE_SETUP_DONE = true

[pytanis]
PRETALX_EVENT_NAME = "pyconde-pydata-2025"
LIVESTREAMS_SHEET_ID = ""
LIVESTREAMS_WORKSHEET_NAME = ""

[logging]
LOG_LEVEL = "INFO"

# =====
# used by discord_bot/conference_setup.py script. [role_colors] must match the values in [roles]
[role_colors]
Organiser = "#ff9b00"  # orange
Volunteer = "#fac800"  # yellow
Attendee = "#3778be"  # blue
Speaker = "#00c8e1"  # mid blue
Session-Chair = "#a2d9ef"  # light blue
Sponsor = "#e199c3"  # light pink
On-Site = "#00aa41"  # green
Remote = "#96dc00"  # light green

# =====
# fill by running discord_bot/conference_setup.py
[roles]
Organiser = 1362862779173961919
Volunteer = 1362862780373405849
Attendee = 1362862781401010438
Speaker = 1362862782214705225
Session-Chair = 1362862783732908142
Sponsor = 1362862785096323073
On-Site = 1362862786258145473
Remote = 1362862788103635135

[registration]
REG_CHANNEL_ID = 1363223311043006605
REG_HELP_CHANNEL_ID = 1363223312460943702
# =====
REG_LOG_CHANNEL_ID = 1216373483114598491


[job_board]
JOB_BOARD_CHANNEL_ID = 1363984069553295531
JOB_BOARD_TESTING = false

[tito]
TITO_BASE_URL="https://val.pycon.de"

[programme_notifications]
timezone = "Europe/Berlin"
timewarp = false  # true for testing
conference_days_first = "2025-04-23"
conference_days_last = "2025-04-25"
conference_afternoon_session_start_time = 13
pretalx_event_name = "pyconde-pydata-2025"
pretalx_schedule_url = "https://pretalx.com/api/events/pyconde-pydata-2025/schedules/latest/"
pretalx_talk_url = "https://pretalx.com/pyconde-pydata-2025/talk/{code}"
# conference_website_session_base_url = "https://2025.pycon.de/program/{slug}"
# conference_website_api_session_url = "https://2025.pycon.de/program/{code}"
slido_url = "https://app.sli.do/event/24bWdyRSGod8DbRpGHcThr"

[[programme_notifications.notification_channels]]
webhook_id = "PROGRAMME_NOTIFICATIONS"
include_channel_in_embeds = true

# Zeiss Plenary (Spectrum) channel: 3893
[programme_notifications.rooms.3893]
webhook_id = "ROOM_3893"
discord_channel_id = "1363604787832164363"
slido_room_url = "https://app.sli.do/event/24bWdyRSGod8DbRpGHcThr/?section=b1cdcda9-83b7-446d-b822-d6e3946a8116"

# Titanium3 channel: 3894
[programme_notifications.rooms.3894]
webhook_id = "ROOM_3894"
discord_channel_id = "1363604791413968988"
slido_room_url = "https://app.sli.do/event/24bWdyRSGod8DbRpGHcThr/?section=38f2af37-c3e4-4f42-a44a-9e3bbaf30144"

# Helium3 channel: 3895
[programme_notifications.rooms.3895]
webhook_id = "ROOM_3895"
discord_channel_id = "1363604794757091469"
slido_room_url = "https://app.sli.do/event/24bWdyRSGod8DbRpGHcThr/?section=1798fbdb-1445-468f-b5e6-21e8b975b5ca"

# Platinum3 channel: 3896
[programme_notifications.rooms.3896]
webhook_id = "ROOM_3896"
discord_channel_id = "1363604799500714127"
slido_room_url = "https://app.sli.do/event/24bWdyRSGod8DbRpGHcThr/?section=d7121ad8-0a89-41de-9357-368e208891ed"

# Europium2 channel: 3897
[programme_notifications.rooms.3897]
webhook_id = "ROOM_3897"
discord_channel_id = "1363604802776469624"
slido_room_url = "https://app.sli.do/event/24bWdyRSGod8DbRpGHcThr/?section=dfeb8cf1-5ed7-4e37-b42e-d802c24c31bf"

# Hassium channel: 3898
[programme_notifications.rooms.3898]
webhook_id = "ROOM_3898"
discord_channel_id = "1363604805754556679"
slido_room_url = "https://app.sli.do/event/24bWdyRSGod8DbRpGHcThr/?section=371b2a34-3c32-4c3c-b413-dc475c413709"

# Palladium channel: 3899
[programme_notifications.rooms.3899]
webhook_id = "ROOM_3899"
discord_channel_id = "1363604808375734435"
slido_room_url = "https://app.sli.do/event/24bWdyRSGod8DbRpGHcThr/?section=ca68af75-c203-484d-bfbf-e5d11bd46c5b"

# Ferrum channel: 3900
[programme_notifications.rooms.3900]
webhook_id = "ROOM_3900"
discord_channel_id = "1363604811060351116"
slido_room_url = "https://app.sli.do/event/24bWdyRSGod8DbRpGHcThr/?section=2151c07b-fcee-4114-81ba-1ba6dc5773cb"

# Dynamicum channel: 3901
[programme_notifications.rooms.3901]
webhook_id = "ROOM_3901"
discord_channel_id = "1363604813937643671"
slido_room_url = "https://app.sli.do/event/24bWdyRSGod8DbRpGHcThr/?section=33ccab25-4f24-42b9-8dce-8e1dcbbe190b"

# Carbonium channel: 3973
[programme_notifications.rooms.3973]
webhook_id = "ROOM_3973"
discord_channel_id = "1363604817007870154"
slido_room_url = ""

# OpenSpace channel: 4084
[programme_notifications.rooms.4084]
webhook_id = "ROOM_4084"
discord_channel_id = "1363604827455881488"
slido_room_url = ""
