[conference]
CONFERENCE_NAME = "PyCon DE & PyData 2025"
CONFERENCE_YEAR = 2025
VOLUNTEER_SHIRT_COLOR = "cream"

[server]
GUILD = 955933777706762280
TESTING = true

[logging]
LOG_LEVEL = "INFO"

# =====
# used by discord_bot/conference_setup.py script. [role_colors] must match the values in [roles]
[role_colors]
Organiser = "#ff9b00"  # orange
Volunteer = "#fac800"  # yellow
Attendee = "#3778be"  # blue
Speaker = "#00c8e1"  # mid blue
Session-Chair = "#a2d9ef"  # light blue
Sponsor = "#e199c3"  # light pink
On-Site = "#00aa41"  # green
Remote = "#96dc00"  # light green

[pytanis]
PRETALX_EVENT_NAME = "pyconde-pydata-2025"

# =====
# fill by running discord_bot/conference_setup.py
[roles]
Organiser = ""
Volunteer = ""
Attendee = ""
Speaker = ""
Session-Chair = ""
Sponsor = ""
On-Site = ""
Remote = ""

[registration]
REG_CHANNEL_ID = ""
REG_HELP_CHANNEL_ID = ""
REG_LOG_CHANNEL_ID = ""

# =====


[job_board]
JOB_BOARD_CHANNEL_ID=1228683389888892980
JOB_BOARD_TESTING = false

[tito]
TITO_BASE_URL="https://val.pycon.de"


[programme_notifications]
timezone = "Europe/Berlin"
timewarp = false  # true for testing
conference_days_first = "2024-04-22"
conference_days_last = "2024-04-24"
pretalx_schedule_url = "https://pretalx.com/api/events/pyconde-pydata-2024/schedules/latest/"
conference_website_session_base_url = "https://2024.pycon.de/program/{slug}"
conference_website_api_session_url = "https://2024.pycon.de/program/{code}"
slido_url = "https://app.sli.do/event/m2rb5rZWkVCvarCFemtqoe"

# we do not need this webhook. not really sure what it should be for
# [[programme_notifications.notification_channels]]
# webhook_id = "PYTHON_DISCORD"
# include_channel_in_embeds = false

[[programme_notifications.notification_channels]]
webhook_id = "PROGRAMME_NOTIFICATIONS"
include_channel_in_embeds = true

# Rooms from pretalx
# KUPPELSAAL: 2578 in pretalx
[programme_notifications.rooms.2578]
webhook_id = "ROOM_2578"
discord_channel_id = "1225453671152877680"
survey_url = "https://survey.sci-an.com/UZpiArTDj7OzJsAU?s=7"

# livestreams are hidden in env vars. add the livestream links to .secrets
[programme_notifications.rooms.2578.livestreams]
"2024-04-22" = "LIVESTREAM_URL_KUPPELSAAL_DAY_1"
"2024-04-23" = "LIVESTREAM_URL_KUPPELSAAL_DAY_2"
"2024-04-24" = "LIVESTREAM_URL_KUPPELSAAL_DAY_3"

# B09: 2579
[programme_notifications.rooms.2579]
webhook_id = "ROOM_2579"
discord_channel_id = "1225453705910816868"
survey_url = "https://survey.sci-an.com/UZpiArTDj7OzJsAU?s=4"

[programme_notifications.rooms.2579.livestreams]
"2024-04-22" = "LIVESTREAM_URL_B09_DAY_1"
"2024-04-23" = "LIVESTREAM_URL_B09_DAY_2"
"2024-04-24" = "LIVESTREAM_URL_B09_DAY_3"

# B07-B08: 2580
[programme_notifications.rooms.2580]
webhook_id = "ROOM_2580"
discord_channel_id = "1225454000800006144"
survey_url = "https://survey.sci-an.com/UZpiArTDj7OzJsAU?s=5"

[programme_notifications.rooms.2580.livestreams]
"2024-04-22" = "LIVESTREAM_URL_B07_08_DAY_1"
"2024-04-23" = "LIVESTREAM_URL_B07_08_DAY_2"
"2024-04-24" = "LIVESTREAM_URL_B07_08_DAY_3"

# B05-B06: 2581
[programme_notifications.rooms.2581]
webhook_id = "ROOM_2581"
discord_channel_id = "1225454340513464340"
survey_url = "https://survey.sci-an.com/UZpiArTDj7OzJsAU?s=6"

[programme_notifications.rooms.2581.livestreams]
"2024-04-22" = "LIVESTREAM_URL_B05_06_DAY_1"
"2024-04-23" = "LIVESTREAM_URL_B05_06_DAY_2"
"2024-04-24" = "LIVESTREAM_URL_B05_06_DAY_3"

# A1: 2582
[programme_notifications.rooms.2582]
webhook_id = "ROOM_2582"
discord_channel_id = "1225454099533791303"
survey_url = "https://survey.sci-an.com/UZpiArTDj7OzJsAU?s=3"

[programme_notifications.rooms.2582.livestreams]
"2024-04-22" = "LIVESTREAM_URL_A1_DAY_1"
"2024-04-23" = "LIVESTREAM_URL_A1_DAY_2"
"2024-04-24" = "LIVESTREAM_URL_A1_DAY_3"

# A03-A04: 2583
[programme_notifications.rooms.2583]
webhook_id = "ROOM_2583"
discord_channel_id = "1225454458935181493"
survey_url = "https://survey.sci-an.com/UZpiArTDj7OzJsAU?s=1"

[programme_notifications.rooms.2583.livestreams]
"2024-04-22" = "LIVESTREAM_URL_A03_04_DAY_1"
"2024-04-23" = "LIVESTREAM_URL_A03_04_DAY_2"
"2024-04-24" = "LIVESTREAM_URL_A03_04_DAY_3"

# A05-A06: 2584
[programme_notifications.rooms.2584]
webhook_id = "ROOM_2584"
discord_channel_id = "1225453715079827577"
survey_url = "https://survey.sci-an.com/UZpiArTDj7OzJsAU?s=2"

[programme_notifications.rooms.2584.livestreams]
"2024-04-22" = "LIVESTREAM_URL_A05_06_DAY_1"
"2024-04-23" = "LIVESTREAM_URL_A05_06_DAY_2"
"2024-04-24" = "LIVESTREAM_URL_A05_06_DAY_3"
