services:
  EuroPythonBot:
    image: europythonbot
    build: .
    volumes:
      - type: bind
        source: /home/ec2-user/discord/.secrets
        target: /home/bot/EuroPythonBot/.secrets
        read_only: true
      - type: bind
        source: /home/ec2-user/registered_log.txt
        target: /home/bot/registered_log.txt
        read_only: false
    # read all container only logs with
    # journalctl -u docker IMAGE_NAME=europythonbot -f
    logging:
      driver: journald
    restart: unless-stopped
