services:
  EuroPythonBot:
    image: europythonbot
    build:
      context: .
    env_file:
      - /root/.secrets
    volumes:
      - type: bind
        source: prod-config.toml
        target: /home/bot/prod-config.toml
        read_only: true

      - type: bind
        source: /root/livestreams.toml
        target: /home/bot/livestreams.toml
        read_only: true

      - type: bind
        source: /home/bot/registered_log.txt
        target: /home/bot/registered_log.txt
        read_only: false

      - type: bind
        source: /home/bot/schedule_cache.json
        target: /home/bot/schedule_cache.json
        read_only: false

      - type: bind
        source: /home/bot/pretix_cache.json
        target: /home/bot/pretix_cache.json
        read_only: false

    # read all container only logs with
    # journalctl -u docker IMAGE_NAME=europythonbot -f
    logging:
      driver: journald
    restart: unless-stopped
