services:
  EuroPythonBot:
    image: europythonbot
    build:
      context: .
      args:
        - CONFIG_FILE=prod-config.toml
    environment:
      - CONFIG_FILE=prod-config.toml
    env_file:
      - /etc/EuroPython/discord/.secrets
    volumes:
      - type: bind
        source: /etc/EuroPython/livestreams/livestreams.toml
        target: /home/bot/livestreams.toml
        read_only: true

      - type: bind
        source: /home/bot/registered_log.txt
        target: /home/bot/registered_log.txt
        read_only: false

      - type: bind
        source: /home/bot/schedule.json
        target: /home/bot/schedule.json
        read_only: false

      - type: bind
        source: /home/bot/pretix_cache.json
        target: /home/bot/pretix_cache.json
        read_only: false

    # read all container only logs with
    # journalctl -u docker IMAGE_NAME=europythonbot -f
    logging:
      driver: journald
    restart: unless-stopped
