services:
  EuroPythonBot:
    image: europythonbot
    build: .
    volumes:
      - type: bind
        source: ./.secrets
        target: /home/bot/.secrets
        read_only: true

    restart: unless-stopped
