services:
  PyConESBot:
    image: pyconesbot
    build: .
    volumes:
      - type: bind
        source: /etc/PyConES/discord/.secrets
        target: /home/bot/.secrets
        read_only: true

      - type: bind
        source: /etc/PyConES/livestreams/livestreams.toml
        target: /home/bot/livestreams.toml
        read_only: true

      - type: bind
        source: /home/bot/registered_log.txt
        target: /home/bot/registered_log.txt
        read_only: false

      - type: bind
        source: /home/bot/schedule.json
        target: /home/bot/schedule.json
        read_only: false

      - type: bind
        source: /home/bot/pretix_cache.json
        target: /home/bot/pretix_cache.json
        read_only: false

    # read all container only logs with
    # journalctl -u docker IMAGE_NAME=pyconesbot -f
    logging:
      driver: journald
    restart: unless-stopped
