services:
  EuroPythonBot:
    image: europythonbot
    build: .
    volumes:
    # Secrets should be updated at this path and container restarted
    # to reload the secrets
      - /root/discord/.secrets:/home/bot/.secrets:ro

    restart: unless-stopped
