services:
  DiscordBot:
    image: discordbot
    build: .
    volumes:
      - type: bind
        source: /etc/DiscrodBot/discord/.secrets
        target: /home/bot/.secrets
        read_only: true
      - type: bind
        source: /home/bot/registered_log.txt
        target: /home/bot/registered_log.txt
        read_only: false
      - type: bind
        source: /home/bot/posted_jobs.txt
        target: /home/bot/posted_jobs.txt
        read_only: false
    # read all container only logs with
    # journalctl -u docker IMAGE_NAME=discordbot -f
    logging:
      driver: journald
    restart: unless-stopped
