# default section - currently just a test
defaults:
  - hello: world

# values for the bot
bot:
  token: MTEwNzY4NzU5ODU0MzA4MTQ5Mg.GIwo_s.HLSkIX5OR_TMcq0aNPTUM6JjzC3VDd8h4w-t28
  server_id: 1108439633789984930
  # for debugging the bot can repeat anything it heard
  echo_mode: true

# define channels for the bot to listen for specific actions
discord_channels:
  # this onboarding channel: The bot will say hello to new users
  # and request the ticket id
  onboard_channel_name: general
  # here we will have the

# roles known to the bot
discord_role_names:
  attendant: new role


