# default section - currently just a test
defaults:
  - hello: world

# values for the bot
# values with "*" will be read from a ".env" file
# with an uppercase name that is combined from the group and key
# for example, the bot token is called DISCORD_BOT_TOKEN
discord_bot:
  token: "*"
  # for debugging the bot can repeat anything it heard
  echo_mode: true

discord:
  server_id: "*"

# define channels for the bot to listen for specific actions
discord_channels:
  # this onboarding channel: The bot will say hello to new users
  # and request the ticket id
  onboard_channel_name: general
  # here we will have the

# roles known to the bot
discord_role_names:
  attendant: new role


