[rooms.treboada]
name = "Treboada"
"2024-10-05" = "https://replay.teltek.es/live/event/iframe/66fce053af77a7003666a32e"
"2024-10-06" = "https://replay.teltek.es/live/event/iframe/66fce053af77a7003666a32e"

[rooms.saraiba]
name = "Saraiba"
"2024-10-05" = "https://replay.teltek.es/live/event/iframe/66fcdd0aaf77a7003666a325"
"2024-10-06" = "https://replay.teltek.es/live/event/iframe/66fcdd0aaf77a7003666a325"

[rooms.poalla]
name = "Poalla"
"2024-10-05" = "https://replay.teltek.es/live/event/iframe/66fcdfeaaf77a700322d9a59"
"2024-10-06" = "https://replay.teltek.es/live/event/iframe/66fcdfeaaf77a700322d9a59"

[rooms.orballo]
name = "Orballo"
"2024-10-05" = "https://replay.teltek.es/live/event/iframe/66fce11baf77a700322d9a61"
"2024-10-06" = "https://replay.teltek.es/live/event/iframe/66fce11baf77a700322d9a61"
