[rooms.forum_hall]
name = "Forum Hall"
"2024-07-10" = "https://www.youtube.com/watch?v=1"
"2024-07-11" = "https://www.youtube.com/watch?v=2"
"2024-07-12" = "https://www.youtube.com/watch?v=3"

[rooms.north_hall]
name = "North Hall"
"2024-07-10" = "https://www.youtube.com/watch?v=4"
"2024-07-11" = "https://www.youtube.com/watch?v=5"
"2024-07-12" = "https://www.youtube.com/watch?v=6"

[rooms.south_hall_2a]
name = "South Hall 2A"
"2024-07-10" = "https://www.youtube.com/watch?v=7"
"2024-07-11" = "https://www.youtube.com/watch?v=8"
"2024-07-12" = "https://www.youtube.com/watch?v=9"

[rooms.south_hall_2b]
name = "South Hall 2B"
"2024-07-10" = "https://www.youtube.com/watch?v=10"
"2024-07-11" = "https://www.youtube.com/watch?v=11"
"2024-07-12" = "https://www.youtube.com/watch?v=12"

[rooms.terrace_2a]
name = "Terrace 2A"
"2024-07-10" = "https://www.youtube.com/watch?v=13"
"2024-07-11" = "https://www.youtube.com/watch?v=14"
"2024-07-12" = "https://www.youtube.com/watch?v=15"

[rooms.terrace_2b]
name = "Terrace 2B"
"2024-07-10" = "https://www.youtube.com/watch?v=16"
"2024-07-11" = "https://www.youtube.com/watch?v=17"
"2024-07-12" = "https://www.youtube.com/watch?v=18"