[rooms.forum_hall]
name = "Forum Hall"
"2024-07-10" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2024-07-11" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2024-07-12" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"

[rooms.north_hall]
name = "North Hall"
"2024-07-10" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2024-07-11" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2024-07-12" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"

[rooms.south_hall_2a]
name = "South Hall 2A"
"2024-07-10" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2024-07-11" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2024-07-12" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"

[rooms.south_hall_2b]
name = "South Hall 2B"
"2024-07-10" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2024-07-11" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2024-07-12" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"

[rooms.terrace_2a]
name = "Terrace 2A"
"2024-07-10" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2024-07-11" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2024-07-12" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"

[rooms.terrace_2b]
name = "Terrace 2B"
"2024-07-10" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2024-07-11" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2024-07-12" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
