log_level = "INFO"

[registration]
registration_form_channel_name = "registration-form"
registration_help_channel_name = "registration-help"
registration_log_channel_name = "registration-log"

pretix_base_url = "http://localhost:8080"

registered_cache_file = "registered_log.txt"
pretix_cache_file = "pretix_cache.json"

[registration.item_to_roles]
# onsite participants
"Business" = ["Participants", "Onsite Participants"]
"Personal" = ["Participants", "Onsite Participants"]
"Education" = ["Participants", "Onsite Participants"]
"Community Contributors" = ["Participants", "Onsite Participants"]
"Grant ticket" = ["PARTICIPANTS", "Onsite Participants"]
# remote participants
"Remote Participation Ticket" = ["Participants", "Remote Participants"]
"Remote Grant ticket" = ["Participants", "Remote Participants"]
"Remote Community Organiser" = ["Participants", "Remote Participants"]
# sponsors
"Sponsor Conference Pass" = ["Participants", "Onsite Participants", "Sponsors"]
# speakers
"Presenter" = ["Participants", "Onsite Participants", "Speakers"]

[registration.variation_to_roles]
"Volunteer" = ["Volunteers"]

[program_notifications]
# UTC offset in hours (e.g. 2 for CEST)
api_url = "https://static.europython.eu/programme/ep2025/releases/current/schedule.json"
schedule_cache_file = "schedule_cache.json"
livestream_url_file = "test-livestreams.toml"
main_notification_channel_name = "programme-notifications"

# optional simulated start time for testing program notifications
simulated_start_time = "2025-07-14T09:15:00+02:00"

# optional fast mode for faster testing of program notifications
# will only take effect if simulated_start_time is set
fast_mode = true

[program_notifications.rooms_to_channel_names]
"Forum Hall" = "forum-hall"
"South Hall 2A" = "south-hall-2a"
"South Hall 2B" = "south-hall-2b"
"North Hall" = "north-hall"
"Terrace 2A" = "terrace-2a"
"Terrace 2B" = "terrace-2b"
"Exhibit Hall" = "exhibit-hall"

[guild_statistics]
required_role = "Organizers"
