[rooms.s1]
name = "S1"
"2024-07-10" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2024-07-11" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2024-07-12" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"

[rooms.s2]
name = "S2"
"2024-07-10" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2024-07-11" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2024-07-12" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"

[rooms.s3a]
name = "S3A"
"2024-07-10" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2024-07-11" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2024-07-12" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"

[rooms.s3b]
name = "S3B"
"2024-07-10" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2024-07-11" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2024-07-12" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"

[rooms.s4]
name = "S4"
"2024-07-10" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2024-07-11" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2024-07-12" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
