[rooms.s1]
name = "S1"
"2026-07-15" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2026-07-16" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2026-07-17" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"

[rooms.s2]
name = "S2"
"2026-07-15" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2026-07-16" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2026-07-17" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"

[rooms.s3a]
name = "S3A"
"2026-07-15" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2026-07-16" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2026-07-17" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"

[rooms.s3b]
name = "S3B"
"2026-07-15" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2026-07-16" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2026-07-17" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"

[rooms.s4]
name = "S4"
"2026-07-15" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2026-07-16" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
"2026-07-17" = "https://www.youtube.com/watch?v=b7wIYTCCa2k"
