[server]
GUILD=12345678

[registration]
REG_CHANNEL_ID=12345678
REG_HELP_CHANNEL_ID=12345678
REG_LOG_CHANNEL_ID=12345678

[pretix]
PRETIX_BASE_URL = "https://fake_url.eu"
TICKET_TO_ROLES_JSON = "ticket_to_roles_staging.json"
