[server]
GUILD=1108439633789984930

[registration]
REG_CHANNEL_ID=1121867356629631026
REG_HELP_CHANNEL_ID=1121867378347757609
REG_LOG_CHANNEL_ID=1124090225367466124

[pretix]
PRETIX_BASE_URL = "https://pretix.eu/api/v1/organizers/europython/events/ep2023"
TICKET_TO_ROLES_JSON = "ticket_to_roles_prod.json"

[logging]
LOG_LEVEL = "INFO"
