[roles]
ORGANISERS = 1253767144286588990
VOLUNTEERS = 1253767144286588989
VOLUNTEERS_ONSITE = 1253767144286588988
VOLUNTEERS_REMOTE = 1253767144265482289
SPEAKERS = 1253767144265482288
SPONSORS = 1253767144265482287
PARTICIPANTS = 1253767144265482285
PARTICIPANTS_ONSITE = 1253767144265482284
PARTICIPANTS_REMOTE = 1253767144265482283

[ticket_to_role]
# onsite participants
"Business" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Community Contributors" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Education" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Personal" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Grant ticket" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
# remote participants
"Remote Community Organiser" = ["PARTICIPANTS", "PARTICIPANTS_REMOTE"]
"Remote Grant Ticket" = ["PARTICIPANTS", "PARTICIPANTS_REMOTE"]
"Remote Participation Ticket" = ["PARTICIPANTS", "PARTICIPANTS_REMOTE"]
# sponsors
"Gold Sponsorship Package" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE", "SPONSORS"]
"Sponsor Conference Pass" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE", "SPONSORS"]
# speakers
"Presenter" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE", "SPEAKERS"]

[registration]
REG_CHANNEL_ID = 1253767145725235229
REG_HELP_CHANNEL_ID = 1254041880446894082
REG_LOG_CHANNEL_ID = 1253767146211901450
REGISTERED_LOG_FILE = "registered_log.txt"

[pretix]
PRETIX_BASE_URL = "https://pretix.eu/api/v1/organizers/europython/events/ep2024"

[logging]
LOG_LEVEL = "INFO"

[program_notifications]
# UTC offset in hours (e.g. 2 for CEST)
timezone_offset = 2
api_url = "https://programapi24.europython.eu/2024/schedule.json"
schedule_cache_file = "schedule.json"

# optional testing configuration
# simulated_start_time = "2024-07-10T07:30:00"
# time_multiplier = 60

[program_notifications.rooms.all_rooms]
name = "All Rooms"
channel_id = "1234839795260330064"

[program_notifications.rooms.forum_hall]
name = "Forum Hall"
channel_id = "1234839841116782642"

[program_notifications.rooms.south_hall_2a]
name = "South Hall 2A"
channel_id = "1234839873685295175"

[program_notifications.rooms.south_hall_2b]
name = "South Hall 2B"
channel_id = "1234839903968301178"

[program_notifications.rooms.north_hall]
name = "North Hall"
channel_id = "1234839930358988840"

[program_notifications.rooms.terrace_2a]
name = "Terrace 2A"
channel_id = "1234839950764277793"

[program_notifications.rooms.terrace_2b]
name = "Terrace 2B"
channel_id = "1234839969369952378"

[program_notifications.rooms.exhibit_hall]
name = "Exhibit Hall"
channel_id = "1252295932154740746"
