[server]
GUILD=955933777706762280

[roles]
ORGANISERS=1229442731227484188
VOLUNTEERS=1164258157833490512
VOLUNTEERS_REMOTE=1227325517900943513
SPEAKERS=1164258330567516200
SPONSORS=1164258080477945886
ATTENDEE=1164258218655096884
ONSITE=1229516503951347825
REMOTE=1164258270605754428

[registration]
REG_CHANNEL_ID=1216372858993901708
REG_HELP_CHANNEL_ID=1216373397681078342
REG_LOG_CHANNEL_ID=1216373483114598491

[job_board]
JOB_BOARD_CHANNEL_ID=1228683389888892980
JOB_BOARD_TESTING = false

# [pretix]
# PRETIX_BASE_URL = "https://pretix.eu/api/v1/organizers/europython/events/ep2023"
# TICKET_TO_ROLES_JSON = "ticket_to_roles_prod.json"

[tito]
TITO_BASE_URL="https://val.pycon.de"

[logging]
LOG_LEVEL = "INFO"

[programme_notifications]
timezone = "Europe/Berlin"
timewarp = false  # true for testing
conference_days_first = "2024-04-22"
conference_days_last = "2024-04-24"
pretalx_schedule_url = "https://pretalx.com/api/events/pyconde-pydata-2024/schedules/latest/"
conference_website_session_base_url = "https://2024.pycon.de/program/{slug}"
conference_website_api_session_url = "https://2024.pycon.de/program/{code}"

# we do not need this webhook. not really sure what it should be for
# [[programme_notifications.notification_channels]]
# webhook_id = "PYTHON_DISCORD"
# include_channel_in_embeds = false

[[programme_notifications.notification_channels]]
webhook_id = "PROGRAMME_NOTIFICATIONS"
include_channel_in_embeds = true

# Rooms from pretalx
# KUPPELSAAL: 2578 in pretalx
[programme_notifications.rooms.2578]
webhook_id = "ROOM_2578"
discord_channel_id = "1225453671152877680"

[programme_notifications.rooms.2578.livestreams]
# TODO: update URLs
"2024-04-22" = "https://2024.pycon.de/live"
"2024-04-23" = "https://2024.pycon.de/live"
"2024-04-24" = "https://2024.pycon.de/live"

# B09: 2579
[programme_notifications.rooms.2579]
webhook_id = "ROOM_2579"
discord_channel_id = "1225453705910816868"

[programme_notifications.rooms.2579.livestreams]
# TODO: update URLs
"2024-04-22" = "https://2024.pycon.de/live"
"2024-04-23" = "https://2024.pycon.de/live"
"2024-04-24" = "https://2024.pycon.de/live"

# B07-B08: 2580
[programme_notifications.rooms.2580]
webhook_id = "ROOM_2580"
discord_channel_id = "1225454000800006144"

[programme_notifications.rooms.2580.livestreams]
# TODO: update URLs
"2024-04-22" = "https://2024.pycon.de/live"
"2024-04-23" = "https://2024.pycon.de/live"
"2024-04-24" = "https://2024.pycon.de/live"

# B05-B06: 2581
[programme_notifications.rooms.2581]
webhook_id = "ROOM_2581"
discord_channel_id = "1225454340513464340"

[programme_notifications.rooms.2581.livestreams]
# TODO: update URLs
"2024-04-22" = "https://2024.pycon.de/live"
"2024-04-23" = "https://2024.pycon.de/live"
"2024-04-24" = "https://2024.pycon.de/live"

# A1: 2582
[programme_notifications.rooms.2582]
webhook_id = "ROOM_2582"
discord_channel_id = "1225454099533791303"

[programme_notifications.rooms.2582.livestreams]
# TODO: update URLs
"2024-04-22" = "https://2024.pycon.de/live"
"2024-04-23" = "https://2024.pycon.de/live"
"2024-04-24" = "https://2024.pycon.de/live"

# A03-A04: 2583
[programme_notifications.rooms.2583]
webhook_id = "ROOM_2583"
discord_channel_id = "1225454458935181493"

[programme_notifications.rooms.2583.livestreams]
# TODO: update URLs
"2024-04-22" = "https://2024.pycon.de/live"
"2024-04-23" = "https://2024.pycon.de/live"
"2024-04-24" = "https://2024.pycon.de/live"

# A05-A06: 2584
[programme_notifications.rooms.2584]
webhook_id = "ROOM_2584"
discord_channel_id = "1225453715079827577"

[programme_notifications.rooms.2584.livestreams]
# TODO: update URLs
"2024-04-22" = "https://2024.pycon.de/live"
"2024-04-23" = "https://2024.pycon.de/live"
"2024-04-24" = "https://2024.pycon.de/live"
