[server]
GUILD=1120766458528542794

[registration]
REG_CHANNEL_ID=1120789543000477818
REG_HELP_CHANNEL_ID=1122535065377837116
REG_LOG_CHANNEL_ID=1120791994789265675

[pretix]
PRETIX_BASE_URL = "https://pretix.eu/api/v1/organizers/europython/events/ep2023"
TICKET_TO_ROLES_JSON = "ticket_to_roles_prod.json"

[logging]
LOG_LEVEL = "INFO"
