[server]
GUILD=''

[registration]
REG_CHANNEL_ID=''
REG_HELP_CHANNEL_ID=''
REG_LOG_CHANNEL_ID=''

[pretix]
PRETIX_BASE_URL = ''
CHECKINLIST_ID = ''

[ticket_to_roles]
Business-Conference = ''
Personal-Conference = ''
Presenter-Speaker = ''
