[roles]
ORGANISERS = 1234981466681774117
VOLUNTEERS = 1234981466681774118
VOLUNTEERS_ONSITE = 1234981466681774118
VOLUNTEERS_REMOTE = 1234981466681774118
SPEAKERS = 1289585935238828073
SPONSORS = 1289586348294148117
PARTICIPANTS = 1234981466681774111
PARTICIPANTS_ONSITE = 1289586561977159760
PARTICIPANTS_REMOTE = 1289586925216206879

[ticket_to_role]
# onsite participants
"Collaborators" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Community Contributors" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Education" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Personal" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Grants" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Diversity" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Volunteers" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE", "VOLUNTEERS"]
# early-bird
"Individual Ticket (Early Bird)" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Educational Ticket (Early Bird)" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
# normal tickets
"Individual Ticket" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Bussiness Ticket" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Educational Ticket" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Individual Supporter Ticket" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Business Supporter Ticket" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Individual Ticket Partners" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
# remote participants
"Virtual Only Ticket" = ["PARTICIPANTS", "PARTICIPANTS_REMOTE"]
"Donation Ticket" = ["PARTICIPANTS", "PARTICIPANTS_REMOTE"]
# sponsors
"Sponsors" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE", "SPONSORS"]
# speakers
"Speaker" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE", "SPEAKERS"]

[additional_roles_by_variation]
"Volunteers" = ["VOLUNTEERS"]

[registration]
REG_CHANNEL_ID = 1289589609138753536
REG_HELP_CHANNEL_ID = 1289591481799147610
REG_LOG_CHANNEL_ID = 1289593057800355851
REGISTERED_LOG_FILE = "registered_log.txt"

[pretix]
PRETIX_BASE_URL = "https://pretix.eu/api/v1/organizers/python-spain/events/pycones2024"
PRETIX_CACHE_FILE = "pretix_cache.json"

[logging]
LOG_LEVEL = "INFO"

[program_notifications]
# UTC offset in hours (e.g. 2 for CEST)
timezone_offset = 2
api_url = "https://programapi24.europython.eu/2024/schedule.json"
schedule_cache_file = "schedule.json"
livestream_url_file = "livestreams.toml"

# optional simulated start time for testing program notifications
# simulated_start_time = "2024-07-10T07:30:00"

# optional fast mode for faster testing of program notifications
# will only take effect if simulated_start_time is set
# fast_mode = true

[program_notifications.rooms.main_channel]
name = "Main Channel"
channel_id = "1253767144899084439"

[program_notifications.rooms.forum_hall]
name = "Forum Hall"
channel_id = "1253767145356005407"

[program_notifications.rooms.south_hall_2a]
name = "South Hall 2A"
channel_id = "1253767145356005408"

[program_notifications.rooms.south_hall_2b]
name = "South Hall 2B"
channel_id = "1253767145356005409"

[program_notifications.rooms.north_hall]
name = "North Hall"
channel_id = "1253767145356005410"

[program_notifications.rooms.terrace_2a]
name = "Terrace 2A"
channel_id = "1253767145356005411"

[program_notifications.rooms.terrace_2b]
name = "Terrace 2B"
channel_id = "1253767145356005412"

[program_notifications.rooms.exhibit_hall]
name = "Exhibit Hall"
channel_id = "1257417344221974639"
