[roles]
ORGANISERS = 1234981466681774117
VOLUNTEERS = 1234981466681774118
VOLUNTEERS_ONSITE = 1234981466681774118
VOLUNTEERS_REMOTE = 1234981466681774118
SPEAKERS = 1289585935238828073
SPONSORS = 1289586348294148117
PARTICIPANTS = 1234981466681774111
PARTICIPANTS_ONSITE = 1289586561977159760
PARTICIPANTS_REMOTE = 1289586925216206879

[ticket_to_role]
# onsite participants
"Collaborators" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Community Contributors" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Education" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Personal" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Grants" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Diversity" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Volunteers" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE", "VOLUNTEERS"]
# early-bird
"Individual Ticket (Early Bird)" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Educational Ticket (Early Bird)" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
# normal tickets
"Individual Ticket" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Business Ticket" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Educational Ticket" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Individual Supporter Ticket" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Business Supporter Ticket" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Individual Ticket Partners" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
# remote participants
"Virtual Only Ticket" = ["PARTICIPANTS", "PARTICIPANTS_REMOTE"]
"Donation Ticket" = ["PARTICIPANTS", "PARTICIPANTS_REMOTE"]
# sponsors
"Sponsors" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE", "SPONSORS"]
# speakers
"Speaker" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE", "SPEAKERS"]

[additional_roles_by_variation]
"Volunteers" = ["VOLUNTEERS"]

[registration]
REG_CHANNEL_ID = 1289589609138753536
REG_HELP_CHANNEL_ID = 1289591481799147610
REG_LOG_CHANNEL_ID = 1289593057800355851
REGISTERED_LOG_FILE = "registered_log.txt"

[pretix]
PRETIX_BASE_URL = "https://pretix.eu/api/v1/organizers/python-spain/events/pycones2024"
PRETIX_CACHE_FILE = "pretix_cache.json"

[logging]
LOG_LEVEL = "INFO"

[program_notifications]
# UTC offset in hours (e.g. 2 for CEST)
timezone_offset = 2
api_url = "https://pretalx.com/pycones-2024/schedule/export/schedule.json"
schedule_cache_file = "schedule.json"
livestream_url_file = "livestreams.toml"

# optional simulated start time for testing program notifications
# simulated_start_time = "2024-07-10T07:30:00"

# optional fast mode for faster testing of program notifications
# will only take effect if simulated_start_time is set
# fast_mode = true

[program_notifications.rooms.main_channel]
name = "Main Channel"
channel_id = "1234981466690293849"

[program_notifications.rooms.treboada]
name = "Treboada"
channel_id = "1290374755446292523"

[program_notifications.rooms.poalla]
name = "Poalla"
channel_id = "1290375008119685161"

[program_notifications.rooms.saraiba]
name = "Saraiba"
channel_id = "1290375213820936222"

[program_notifications.rooms.orballo]
name = "Orballo"
channel_id = "1290375406091767808"

[program_notifications.rooms.neboeira]
name = "Neboeira"
channel_id = "1290375569531473962"
