[roles]
ORGANISERS = 1363473647997812778
VOLUNTEERS = 1363473649490853889
VOLUNTEERS_ONSITE = 1331995051093528645
VOLUNTEERS_REMOTE = 1331995051093528644
SPEAKERS = 1331995051093528643
SPONSORS = 1331995051093528642
PARTICIPANTS = 1331995051093528640
PARTICIPANTS_ONSITE = 1331995051093528639
PARTICIPANTS_REMOTE = 1331995051093528638

[ticket_to_role]
# onsite participants
"Business" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Personal" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Education" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Community Contributors" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
"Grant ticket" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE"]
# remote participants
"Remote Participation Ticket" = ["PARTICIPANTS", "PARTICIPANTS_REMOTE"]
"Remote Grant ticket" = ["PARTICIPANTS", "PARTICIPANTS_REMOTE"]
"Remote Community Organiser" = ["PARTICIPANTS", "PARTICIPANTS_REMOTE"]
# sponsors
"Sponsor Conference Pass" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE", "SPONSORS"]
# speakers
"Presenter" = ["PARTICIPANTS", "PARTICIPANTS_ONSITE", "SPEAKERS"]

[additional_roles_by_variation]
"Volunteer" = ["VOLUNTEERS"]

[registration]
REG_CHANNEL_ID = 1363473814029209811
REG_HELP_CHANNEL_ID = 1363473815392354455
REG_LOG_CHANNEL_ID = 1363473816461906007
REGISTERED_LOG_FILE = "registered_log.txt"

[pretix]
PRETIX_BASE_URL = "https://pretix.eu/api/v1/organizers/europython/events/ep2025"
PRETIX_CACHE_FILE = "pretix_cache.json"

[logging]
LOG_LEVEL = "INFO"

[program_notifications]
# UTC offset in hours (e.g. 2 for CEST)
timezone_offset = 2
api_url = "https://programapi24.europython.eu/2024/schedule.json"
schedule_cache_file = "schedule.json"
livestream_url_file = "livestreams.toml"

# optional simulated start time for testing program notifications
# simulated_start_time = "2024-07-10T07:30:00"

# optional fast mode for faster testing of program notifications
# will only take effect if simulated_start_time is set
# fast_mode = true

[program_notifications.rooms.main_channel]
name = "Main Channel"
channel_id = "1363473705455325306"

[program_notifications.rooms.forum_hall]
name = "Forum Hall"
channel_id = "1363473707091366068"

[program_notifications.rooms.south_hall_2a]
name = "South Hall 2A"
channel_id = "1363473708223693012"

[program_notifications.rooms.south_hall_2b]
name = "South Hall 2B"
channel_id = "1363473709377261830"

[program_notifications.rooms.north_hall]
name = "North Hall"
channel_id = "1363473710983680121"

[program_notifications.rooms.terrace_2a]
name = "Terrace 2A"
channel_id = "1363473712124526715"

[program_notifications.rooms.terrace_2b]
name = "Terrace 2B"
channel_id = "1363473713609310268"

[program_notifications.rooms.exhibit_hall]
name = "Exhibit Hall"
channel_id = "1363473714573873263"
