[item_to_role]
# onsite participants
"Business" = ["Participants", "Onsite Participants"]
"Personal" = ["Participants", "Onsite Participants"]
"Education" = ["Participants", "Onsite Participants"]
"Community Contributors" = ["Participants", "Onsite Participants"]
"Grant ticket" = ["PARTICIPANTS", "Onsite Participants"]
# remote participants
"Remote Participation Ticket" = ["Participants", "Remote Participants"]
"Remote Grant ticket" = ["Participants", "Remote Participants"]
"Remote Community Organiser" = ["Participants", "Remote Participants"]
# sponsors
"Sponsor Conference Pass" = ["Participants", "Onsite Participants", "Sponsors"]
# speakers
"Presenter" = ["Participants", "Onsite Participants", "Speakers"]

[variation_to_role]
"Volunteer" = ["Volunteers"]

[registration]
REG_CHANNEL_NAME = "registration-form"
REG_HELP_CHANNEL_NAME = "registration-help"
REG_LOG_CHANNEL_NAME = "registration-log"
REGISTERED_LOG_FILE = "registered_log.txt"

[pretix]
PRETIX_BASE_URL = "https://pretix.eu/api/v1/organizers/europython/events/ep2025-staging"
PRETIX_CACHE_FILE = "pretix_cache.json"

[logging]
LOG_LEVEL = "INFO"

[program_notifications]
# UTC offset in hours (e.g. 2 for CEST)
timezone_offset = 2
api_url = "https://static.europython.eu/programme/ep2025/releases/current/schedule.json"
schedule_cache_file = "schedule.json"
livestream_url_file = "livestreams.toml"

# optional simulated start time for testing program notifications
simulated_start_time = "2025-07-14T09:15:00"

# optional fast mode for faster testing of program notifications
# will only take effect if simulated_start_time is set
fast_mode = true

[program_notifications.rooms.main_channel]
name = "Main Channel"
channel_id = "1360981875421610084"

[program_notifications.rooms.forum_hall]
name = "Forum Hall"
channel_id = "1360981877522956369"

[program_notifications.rooms.south_hall_2a]
name = "South Hall 2A"
channel_id = "1360981879196487730"

[program_notifications.rooms.south_hall_2b]
name = "South Hall 2B"
channel_id = "1360981880584929363"

[program_notifications.rooms.north_hall]
name = "North Hall"
channel_id = "1360981881851478257"

[program_notifications.rooms.terrace_2a]
name = "Terrace 2A"
channel_id = "1360981883411759235"

[program_notifications.rooms.terrace_2b]
name = "Terrace 2B"
channel_id = "1360981884556808382"

[program_notifications.rooms.exhibit_hall]
name = "Exhibit Hall"
channel_id = "1360981885798322288"
