---
- name: Deploy Discord Bot to the server
  hosts: bot_server
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Clone the repository
      git:
        repo: https://github.com/EuroPython/discord.git
        dest: /app
        version: main
        force: yes
