---
- name: Deploy Discord Bot to the server
  hosts: bot_server

  tasks:
    - name: Install Docker & git
      become: true
      yum:
        name: {{ packages }}
        state: present
      vars:
         packages:
            - docker
            - git

    - name: Add 'ec2-user' to docker group
      become: true
      user:
        name: ec2-user
        groups: docker

    - name: Clone repository
      git:
        repo: https://github.com/EuroPython/discord.git
        dest: /home/ec2-user/discord
        depth: 1
        force: yes
        single_branch: yes
        version: deploy-aws

    - name: Create registration_log.txt in bot's home directory
      file:
        path: /home/ec2-user/registered_log.txt
        state: touch
        owner: ec2-user
        group: ec2-user

    - name: Generate '.secrets' file
      template:
        src: .secrets.j2
        dest: /home/ec2-user/discord/.secrets
        owner: ec2-user
        group: ec2-user
        mode: 0600

    - name: Start EuroPythonBot
      shell: "cd /home/ec2-user/discord && docker-compose down && docker-compose up --detach --build"
