---
- name: Deploy Discord Bot to the server
  hosts: bot_server
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Remove old repository
      file:
        path: /app/EuroPython/discord
        state: absent

    - name: Clone the repository
      git:
        repo: git@github.com:EuroPython/discord.git
        dest: /app/EuroPython/discord
        version: add-deploy
        depth: 1
        force: yes
        key_file: /root/.ssh/deploy_key

    - name: Install Pipenv
      pip:
        name: pipenv
        state: latest

    - name: Create Pipenv environment
      shell:
        chdir: /app/EuroPython/discord
        cmd: pipenv install --dev --python /usr/bin/python3

    - name: Install screen
      apt:
        name: screen
        state: present

    - name: Create screen session and start the bot
      shell:
        chdir: /app/EuroPython/discord
        cmd: screen -dmS discord_bot pipenv run /path/to/your_program.py
