---
- name: Deploy Discord Bot to the server
  hosts: bot_server
  vars:
    repository_url: git@github.com:EuroPython/discord.git

  tasks:

    - name: Enable persistent logging for journald
      ini_file:
        path: /etc/systemd/journald.conf
        section: Journal
        option: Storage
        value: persistent
        no_extra_spaces: true
        backup: true


    - name: reload systemd-journald
      systemd:
        name: systemd-journald
        state: restarted 

    - name: Install Docker dependencies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    - name: Install Docker
      block:
        - name: Add Docker GPG key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add Docker repository
          apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
            state: present

        - name: Install Docker
          apt:
            name: docker-ce
            state: present

    - name: Clone repository
      git:
        repo: "{{ repository_url }}"
        dest: /root/discord
        depth: 1
        force: yes
        accept_hostkey: yes
        single_branch: yes
        version: main
        key_file: /root/.ssh/deploy_key

    - name: Ensure registered txt file is present
      shell: "touch /home/bot/registered_log.txt"

    - name: Start EuroPythonBot
      shell: "cd /root/discord && docker compose down && docker compose up --detach --build"
