---
- name: Deploy Discord Bot to the server
  hosts: bot_server
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Create an /app directory
      file:
        path: /app
        state: directory
